In [9]:
%matplotlib notebook
import pandas as pd
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
import pylab

In [10]:
# read csv datasets using TF
CSV_PATH = 'filterdatasetnoname.csv'

dataset = tf.contrib.data.make_csv_dataset(CSV_PATH, batch_size=338)
iter = dataset.make_one_shot_iterator()
next = iter.get_next()

# bellow is a dict with all feature in the datasets
print(next, '\n')
KODERS, TTD, TM, DPRS = next['KODERS'], next['TTD'], next['TM'], next['DPRS']

with  tf.Session() as sess:
    print(sess.run([KODERS, TTD, TM, DPRS]))

OrderedDict([('KODERS', <tf.Tensor 'IteratorGetNext_4:1' shape=(?,) dtype=int32>), ('TTD', <tf.Tensor 'IteratorGetNext_4:3' shape=(?,) dtype=int32>), ('TM', <tf.Tensor 'IteratorGetNext_4:2' shape=(?,) dtype=int32>), ('DPRS', <tf.Tensor 'IteratorGetNext_4:0' shape=(?,) dtype=int32>)])

[array([ 3603115,  3201072,  3173698,  3171216,  3674102,  3171435,
        3173660,  3276028,  3271164,  3276124,  3201251,  3172702,
        3276150,  3671043,  3175315,  3171792, 31727475,  3174509,
        3172758,  3172516,  3671202,  3671209,  3172072,  3674193,
        3172751,  3603082,  3171450,  3671124,  3275060,  3275307,
        3172757,  3171793,  3173496,  3201185,  3172137,  3173120,
        3671207,  3172520,  3671065,  3216285,  3276041,  3174453,
        3674005,  3174525,  3173696,  3275064,  3271104,  3201013,
        3175042,  3175411,  3674015,  3271161,  3171795,  3671223,
        3173051,  3174260,  3173671,  3276135,  3674012,  3276147,
        3174508,  3216429,  3171680,  3171781,  3175363,  3174486,
        3275196,  3275039,  3174517,  3172243,  3175181, 32754035,
        3172749,  3173707,  3671204,  3216396, 31727565,  3172724,
        3171724,  3271046,  3201243,  3175416,  3173014,  3173506,
        3275373,  3173532,  3173084,  3201035,  3171413,  3275053,
        3271024,  3174475,  3216218,  3671205,  3275115,  3671126,
        3172301,  3173645,  3171012,  3171790,  3171757,  3172759,
        3275046,  3603201,  3173682,  3172035,  3671217,  3275390,
        3216389,  3275296,  3173073,  3173025,  3174052,  3671146,
        3674168,  3172206,  3276039,  3671210,  3275392, 32761495,
        3172713,  3276017, 31745165,  3173705,  3275207,  3275263,
        3275083,  3174518,  3175352,  3671021,  3175413,  3674056,
        3171702,  3173372,  3171461,  3174431,  3172094,  3174405,
        3172505,  3175075,  3171676,  3671211,  3171746, 31727535,
        3171034,  3175031,  3174497,  3674013,  3174074,  3172767,
        3175385,  3174282,  3172061,   317541,  3171632,  3275063,
        3171511,  3201240,  3175064,  3172748,  3603010,  3172013,
        3216362,  3174519,  3172531,  3275141,  3173441,  3172735,
        3175412,  3271013,  3173623,  3101002,  3171800,  3603093,
        3171610,  3271162,  3174529,  3201141,  3173543,  3674019,
        3171504,  3275229,  3174351,  3174395,  3171782,  3275130,
        3216423,  3671219,  3171791,  3173014,  3216174,  3275013,
        3671082,  3172024,  3175330,  3271163,  3276154,  3171045,
        3171083,  3173062,  3276151,  3171060,  3271072,  3671203,
        3171768,  3174523,  3172083,  3171785,  3671221,  3171515,
        3171286,  3174015,  3674011,  3674007,  3275274,  3173040,
        3171665,  3173244,  3671136,  3173510,  3171801,  3173580,
        3171574,  3674006,  3175409,  3674009,  3174510,  3216427,
        3172769,  3173036,  3674003,  3173634,  3671076,  3276146,
        3172126,  3674113,  3674016,  3175016,  3671218,  3173656,
        3271126,  3275017,  3174030,  3173704,  3603034,  3174041,
        3171713,  3201126,  3271166,  3276152,  3173699,  3173116,
        3172760,  3174527,  3171802,  3175326,  3275094,  3201061,
        3671214,  3276153,  3201236,  3174522,  3674014,  3171023,
        3172761,  3173131,  3201241,  3216402,  3171621,  3175341,
        3173697,  3171786,  3172765,  3671216, 31717895,  3173695,
        3174026,  3201218,  3671208,  3603060,  3725061,  3174515,
        3674171,  3275052,  3175410,  3173701,  3171798,  3674008,
        3172770,  3275062,  3171072,  3671135, 31717835,  3271115,
        3172520,  3216329,  3173105,  3172050,  3175408,  3175304,
        3175414,  3275024,  3171784,  3173521,  3173474,  3671091,
        3201196,  3671032,  3674071,  3174416,  3175396, 31727475,
        3172553,  3674004,  3174420,  3173612,  3275035,  3275050,
        3172750,  3275057,  3171643,  3674157,  3674018,  3174063,
        3172752,  3171424,  3171796,  3173700,  3671222,  3175374,
        3175407,  3173706,  3671080,  3172746,  3171552, 31727555,
        3171785,  3172590], dtype=int32), array([ 165,  141,   39,   46,  205,  100,  105,  203,  127,   93,   63,
         95,   38,  139,  106,   30,  152,   32,   78,   90,   60,  116,
       1163,  110,    8,   68,   68,   96,   81,   81,  110,   39,   25,
        237,   50,   94,   92,  112,  360,  108,  119,  113,  186,   54,
         61,    0,  312,   61,  164,   35,   32,   92,  522,  136,  295,
        354,    3,   65,   79,   57,  132,   28,   75,   91,   91,  110,
        124,   45,   32,  148,   75,   30,  149,    8,  139,   33,   31,
        265,   69,  707,   28,   37,  959,  201,  124,   34,  240,  141,
         76,   55,  221,   74,  143,  187,  292,  109,   53,  112,  862,
         34,   55,   52,  182,   38,   40,  125,   36,   38,  102,   51,
        456,  723,  123,  193,  145,  280,   90,  102,  267,   41,   96,
        242,   46,   33,  112,   70,   81,   51,  182,   71,   37,   81,
        103,   35,  142,  237,  238,   50,  227,  114,   50,   63,   60,
        117,  174,  168,   27,   73,  304,    0,  154,  354,  165,   32,
         73,    0,   34,   43,  200,   76,  476,  605,  119,    0,   78,
         73,   78,   52,   54,  336,   19,   13,   61,   30,   40,   60,
          0,   83,   47,   27,  235,  125,  219,   68,   32,  138,   65,
         38,   46,  919,  108,  601,   53,  345,  168,   69,   91,  155,
         39,  339,  118,   52,  125,  234,   68,   31,   94,   58,   42,
        151,   42,  245,   30,   96,   74,  448,  180,   44,  100,   20,
         48,  140,  155,   69,   82,   55,   52,   67,    0,  285,   63,
         25,  122,  140,  315,  161,   72,  608,   31,  156,   91,   66,
         77,    0,   40,  320,   77,  159,   27,   77,   28,   42,   45,
          0,    0,  168,  289,  140,    0,   46,  113,  254,   79,  384,
         29,   52,   36,  155,   52,  158,    2,  166,   22,   88,   94,
         37,  335,  148,  219,  114,   70,   25,   88,   55,   40,   38,
          9,   20,    0,   71,  134,   96,   63,  117,  112,  122,  214,
         88,  115,   53,   15,  121,   71,  420,   77,   25,  107,  239,
         60,  109,   47,   61,  221,   86,   88,   20,   54,  107,   50,
         53,   52,   98,  134,  424,   41,   24,   26,   42,   29,  130,
        162,  136,  179,   25,   26,   56,  122,   84], dtype=int32), array([ 375,  325,   29,   10,  634,  189,   48,  437,  141,  161,  129,
         71,   88,  387,  329,   29,  331,   20,  185,   87,   73,   56,
        865,  143,    2,  135,   59,  165,   59,  135,  161,    0,    5,
        370,    0,  267,   40,  220,  127,  203,   90,  175,  316,    0,
        139,    0,  578,   47,  123,   72,   36,   93,  277,   91,  664,
        796,   69,  137,   95,   68,  420,   20,   84,   82,   47,   18,
         77,   68,    3,  482,  206,   50,  562,   37,   56,   20,   55,
        480,  143,  645,   19,    0, 3728,  117,  376,  103,   99,  275,
         39,   31,  179,   14,   74,  333,  647,  191,  127,  137, 1953,
        120,   64,   67,  114,   64,   11,   58,   38,   38,   75,   59,
        176, 1765,  231,  207,  329,  153,  134,   61,  493,   73,  103,
        448,   36,   67,  109,   48,   83,   76,  175,  121,   56,   99,
         33,    1,   89,  367,  180,   13,  154,   63,    1,   94,  114,
        294,   96,   74,   20,   84,  721,    0,  173, 1091,  135,   28,
         46,    0,   71,   59,  360,  218,  989, 1310,  120,   52,  142,
        162,  210,   15,   79,  124,   53,    5,   72,   37,    1,   29,
          0,  113,   98,   33,  252,  190,  603,    4,   18,   96,   78,
         20,   55, 3673,   42,  606,   45,   92,  336,  104,   83,  168,
          9,  178,  177,   28,  117,  496,   87,   47,  141,   94,   36,
         14,   90,  301,   33,  328,  140,  709,   25,    1,  306,    1,
         64,   66,  119,  202,   68,   80,   17,   28,    0,  492,   16,
          6,  305,  292,  535,  605,   99,  578,   45,  437,  297,   59,
         98,    0,    3,  328,   85,  331,   32,   91,   57,   20,   68,
          0,    0,  251,  558,   93,    0,   60,   88,  220,  171,  212,
         27,    4,   64,   58,   63,  175,  129,  685,   45,   79,  137,
         54,  102,  141,  390,  203,  144,  143,   86,   88,   53,   84,
         31,   31,    0,   81,  345,   75,   95,  121,  220,   96,  312,
         68,  130,   91,   29,   96,   41,  245,  161,    0,  222,  344,
         12,   71,  148,   50,  137,  161,   41,   17,   38,  184,   61,
         40,  132,  192,  339,  906,   21,   66,   57,   72,   32,  131,
        506,  188,  520,    0,   12,    4,  114,   79], dtype=int32), array([14, 11,  2,  0, 15,  8,  0, 14, 12,  9, 13, 13, 10, 14, 14,  5, 14,
        0, 13, 12,  9,  0, 15, 11,  0, 12, 10,  9, 12, 12, 12,  0,  0, 14,
        0, 10,  0,  7,  0, 12, 13, 13, 13,  0, 13,  0, 12,  9,  0, 11, 12,
        8,  1, 11, 14, 15,  4, 10, 12, 10, 15,  8,  6,  9,  1,  0, 12, 11,
        3,  0, 11, 11, 12,  8,  4, 12,  1,  8,  1, 13,  6, 11, 15,  0, 15,
        8, 12, 13,  0,  6,  9,  0, 11, 12, 15, 12, 11, 13, 15, 12,  9, 10,
       15,  8,  0, 13, 11,  9, 12, 10, 14, 15,  0,  9, 13,  0, 11, 12, 14,
       11, 10, 12, 10,  5,  9, 11,  9, 12,  0, 11, 11, 12,  4,  0, 14, 14,
        0,  0,  0, 12,  0, 12, 12, 12,  0, 13,  0,  3, 11,  0,  0, 15, 13,
        6, 11,  0,  0, 12, 14, 12, 14, 15,  0,  9, 12, 12, 12,  1, 10, 13,
        2,  0,  9, 12,  0,  9,  0,  6, 13, 10,  1, 12, 15,  0,  5, 11, 12,
       12,  6, 15, 11, 15, 10,  2, 14, 12, 12, 12,  0, 14, 11,  0, 12, 15,
        0,  0, 12, 11,  8,  1, 12, 11, 11, 12, 12, 15,  9,  0, 13,  0,  8,
       13,  0, 12,  0, 12,  0, 11,  0, 15,  9,  0,  8, 13, 14, 15, 12, 15,
       11, 15, 12, 11, 13,  0,  0,  7,  9, 13, 11, 12,  4,  0, 12,  0,  0,
        0, 14, 10,  0, 12, 12, 13, 12, 15,  0,  0,  5, 11, 14, 15,  3, 13,
        9, 12,  3,  1, 15,  4, 13, 12, 10,  6, 11, 12, 11,  3,  9,  7,  0,
       13, 13, 11, 11, 14,  7, 10, 11,  8, 10,  0,  0,  9, 11, 12,  0,  0,
        9, 13,  3, 10, 12, 12, 13, 12,  0,  0, 10, 12, 10, 10,  8, 14, 15,
       13,  0,  9,  0,  8,  9, 14, 15,  2, 12,  0,  0,  0,  0, 10],
      dtype=int32)]

In [11]:
# read csv datasets using TF
CSV_PATH = 'filterdatasetnoname.csv'

dataset = tf.contrib.data.make_csv_dataset(CSV_PATH, batch_size=338)
iter = dataset.make_one_shot_iterator()
next = iter.get_next()

# bellow is a dict with all feature in the datasets
print(next, '\n')
KODERS, TTD, TM, DPRS = next['KODERS'], next['TTD'], next['TM'], next['DPRS']

with  tf.Session() as sess:
    print(sess.run([KODERS, TTD, TM, DPRS]))

OrderedDict([('KODERS', <tf.Tensor 'IteratorGetNext_5:1' shape=(?,) dtype=int32>), ('TTD', <tf.Tensor 'IteratorGetNext_5:3' shape=(?,) dtype=int32>), ('TM', <tf.Tensor 'IteratorGetNext_5:2' shape=(?,) dtype=int32>), ('DPRS', <tf.Tensor 'IteratorGetNext_5:0' shape=(?,) dtype=int32>)])

[array([ 3275130,  3175414,  3174510,  3201251,  3674005,  3171796,
       31727475,  3275064,  3174497,  3216362,  3674168,  3171511,
        3175042,  3671126,  3671204,  3172749,  3171083,  3201061,
        3271072,  3173645,  3275052,  3216396,  3201196,  3674056,
        3671124,  3171786,  3674171,  3172024,  3275115,  3671205,
        3216423,  3173105,  3173014,  3171060,  3171785,  3171216,
        3674011,  3171702, 31745165,  3671021,  3173696,  3174026,
        3172767,  3172748,  3671217,  3216218,  3174351,  3175413,
        3174282,  3171286,  3671214,  3271166,  3216427,  3725061,
        3173707,  3171413,  3175374,  3171632,  3276135,  3671222,
        3175396,   317541,  3172702,  3271126,  3173120,  3174041,
        3275196,  3175031,  3171574,  3173131,  3101002,  3671080,
        3674193,  3174260,  3271164,  3171610,  3674006,  3671208,
        3674018,  3671136,  3671043,  3603010,  3271046,  3671032,
       32754035,  3172760,  3174522,  3173623,  3671082,  3276153,
        3275263,  3175330,  3173244,  3173521,  3174519,  3175409,
        3216429,  3175407,  3671202,  3275207,  3172759,  3674014,
        3172520, 32761495,  3271163,  3275057,  3171802,  3674008,
        3174405,  3172750,  3172206,  3171515,  3172757,  3603060,
        3173025,  3201241,  3172769,  3171424,  3172770,  3173695,
        3201126,  3174395,  3671091,  3175411,  3172126,  3174475,
        3172061,  3173532,  3275050,  3276151,  3172301,  3174523,
        3174509,  3171801,  3172751,  3603115,  3175181,  3171781,
        3172516, 31727565,  3172013,  3671211,  3175385,  3173036,
        3175352,  3275141,  3171012,  3174030,  3175075,  3174420,
        3172765,  3173073,  3275046,  3173062,  3671216,  3201240,
        3275083,  3173704,  3174063,  3171665,  3172761,  3171680,
        3275013,  3174015,  3171795,  3201035,  3674019,  3173682,
        3674016,  3171800,  3674157,  3171552,  3275296,  3175304,
        3674012,  3174416,  3174486,  3174527,  3674102,  3174508,
        3671203,  3172590,  3172243,  3201013,  3276017,  3275062,
        3173612,  3275229,  3173040,  3674015,  3171790,  3674004,
        3174052,  3175363,  3275392,  3171450,  3271104,  3674007,
        3171792,  3171793,  3175064,  3175016,  3171643,  3171461,
        3276154,  3603034,  3172505,  3173660,  3171435,  3275039,
        3671209,  3671221,  3173506,  3172531,  3603201,  3276041,
        3671219,  3172752,  3674071,  3671135,  3671065,  3275390,
        3275035,  3171782,  3172758,  3275094,  3173372,  3671223,
        3173699,  3173697,  3172083,  3172137,  3216329,  3271161,
        3201185,  3171621,  3171785,  3173656,  3171023,  3174525,
        3275017,  3171504,  3173634,  3173701,  3275373,  3671210,
        3216389,  3171746,  3201243,  3171768,  3173706,  3275307,
        3674009,  3172553,  3276146,  3175408,  3216174,  3674113,
        3671207,  3271115,  3172072,  3173116,  3173698,  3674003,
        3171676, 31717835,  3173014,  3174517,  3171724,  3674013,
        3171045,  3276147,  3671076,  3172520,  3271162,  3175341,
        3174453,  3173705,  3172746,  3174518,  3271013,  3174515,
        3173671,  3175412,  3276028,  3201072,  3173580,  3271024,
        3174529, 31727475,  3172050,  3172713,  3175326,  3174431,
        3172735,  3173441,  3173496,  3275053, 31717895,  3172035,
        3171791,  3275063, 31727555,  3171798,  3276150,  3173700,
        3201141,  3171757,  3173084,  3276124,  3216402,  3174074,
        3216285,  3171713,  3172724,  3171072,  3275024,  3671146,
        3173474,  3275274,  3201236,  3173543,  3171034,  3173510,
        3276039,  3201218,  3671218,  3173051,  3172094,  3175410,
       31727535,  3175416,  3603082,  3275060,  3603093,  3175315,
        3171784,  3276152], dtype=int32), array([ 138,   15,   52,   63,  186,   26,   61,    0,   27,  119,  145,
         34,  164,  109,  139,  149,   39,  140,  125,  112,   55,   33,
        107,   81,   96,  166,   88,  345,  292,  187,   65,  214,  959,
         52,  122,   46,   30,  103,   46,   71,   61,  335,    0,   76,
         36,  143,  219,   37,  354,   42,    0,   27,   67,   70,    8,
         76,  130,   73,   65,   29,   47,   32,   95,   91,   94,  320,
        124,  168,  155,   52,   13,  179,  110,  354,  127,   40,   69,
        219,  134,  100,  139,  476,  707,  239,   30,   45,  254,   19,
         53,   46,   70,  168,   44,  420,    0,   82,   28,  162,   60,
        112,   52,   79,  112,   41,   69,   53,    0,   20,   50,   50,
        280,  151,  110,  114,  723,   36,    0,   24,    0,   37,  159,
         68,   25,   35,  315,   74,  165,   34,  107,  118,   53,   31,
         32,   48,    8,  165,   75,   91,   90,   31,  605,   63,  154,
        285,  182,   73,  862,   77,  114,   88,   22,  456,  182,  339,
         88,   43,   81,    0,  424,  180,   29,   75,  601,  245,  522,
        141,   27,   40,   72,   61,   98,   26,   51,   53,   79,  109,
        110,    0,  205,  132,  234,   84,  148,   61,  242,   71,   20,
        125,  448,   32,   34,   86,  123,   91,  267,   68,  312,   96,
         30,   39,  200,  608,   52,  142,   91,   40,  227,  105,  100,
         45,  116,   42,  201,   78,   38,  119,   38,   41,   60,   96,
        360,   38,   54,   32,   78,  289,   35,  136,   28,    2,   94,
         50,  122,   92,  237,   52,   58,  156,  384,   54,   66,  235,
         25,   38,  124,  102,  102,   60,   28,   68,  136,   81,   55,
        221,  140,  115,  108,  161,   92,  117, 1163,   42,   39,   63,
         50,   63,  919,   32,   69,   73,  155,   57,  122,  112,   60,
        158,  113,   33,   25,   51,  336,   25,    3,   54,  203,  141,
        140,  221,    0,  152,   88,   96,  168,  237,   52,   78,   25,
         55,   94,  125,   46,    0,   56,    9,   38,   42,   83,   55,
        240,   93,  155,  304,  108,   77,  265,  134,  121,  193,   77,
         74,  113,   47,  174,   20,   90,  148,   31,  295,  238,   40,
        117,   37,   68,   81,   30,  106,   71,   77], dtype=int32), array([  96,   29,   17,  129,  316,   57,   50,    0,   20,  120,  329,
         71,  123,  191,   56,  562,    9,   93,  117,  137,   88,   20,
        222,   99,  165,  685,   86,   92,  647,  333,   78,  312, 3728,
         28,  114,   10,   33,   33,   36,  121,  139,  102,    0,  218,
         38,   74,  603,   56, 1091,   90,    0,   32,   28,  144,   37,
         39,  131,   46,  137,   32,  148,   28,   71,  297,  267,  328,
         77,   74,  119,    4,    5,  520,  143,  796,  141,    1,  202,
        390,  339,  306,  387,  989,  645,  344,   50,   68,  220,   53,
         45,   60,   48,  336,    1,  245,   52,   68,   20,  506,   73,
        109,   67,  171,  220,   73,  104,   40,    0,   31,   13,   61,
        153,   14,  161,  203, 1765,   64,    0,   66,    0,   54,  331,
          4,    0,   72,  535,   14,  135,  103,  184,  177,  127,   47,
         20,   64,    2,  375,  206,   82,   87,   55, 1310,   94,  173,
        492,  175,  162, 1953,   98,   63,   41,   45,  176,  114,  178,
         79,   59,   83,    0,  906,   25,   27,   84,  606,  301,  277,
        275,   33,   11,   99,   72,  192,   12,   59,   91,   95,   71,
         18,    0,  634,  420,  496,   79,  482,   47,  448,   81,   17,
        190,  709,   36,  120,  161,  231,   47,  493,   59,  578,  328,
         29,    0,  360,  578,  132,   89,   83,    3,  154,   48,  189,
         68,   56,   36,  117,  142,   64,   90,   20,   21,   12,   75,
        127,   38,   38,   18,  185,  558,    1,   91,   57,  129,  141,
          0,   96,   93,  370,   63,   94,  437,  212,    0,   59,  252,
          6,   84,  376,   61,   75,  114,   19,   87,  188,  135,   80,
        137,  292,  130,   42,  605,   40,  121,  865,   20,   29,   16,
          1,   95, 3673,    3,  143,   84,  168,   68,  305,  220,   29,
        175,  175,   67,    0,   76,  124,  143,   69,   79,  437,  325,
         66,  179,    0,  331,   68,  103,  251,  367,   15,  210,    5,
         31,  137,   58,   55,    0,    4,   31,   88,   72,  113,   64,
         99,  161,   58,  721,  203,   85,  480,  345,   96,  207,  161,
        140,   88,   98,   96,    1,  134,  141,   45,  664,  180,   53,
        294,    0,  135,   59,   37,  329,   41,   91], dtype=int32), array([11,  0,  0, 13, 13,  0, 12,  0,  0,  0, 13,  0,  0, 12,  4, 12,  0,
       10, 12, 13, 12, 12,  9, 12,  9, 13, 11,  2, 15, 12, 12, 11, 15,  0,
        0,  0, 11,  4, 10, 11, 13, 15,  0, 12, 11, 11, 15, 11, 15, 12,  0,
       11, 11, 10,  8,  0, 14, 11, 10,  9, 12,  6, 13, 12, 10,  7, 12, 13,
        0,  0,  0, 12, 11, 15, 12,  0, 12, 13, 15, 13, 14, 14, 13, 13, 11,
       12, 13,  2, 10, 12, 11, 14,  0, 12,  9,  0,  8, 15,  9,  9, 10, 12,
        7, 11, 12, 10,  0,  7,  0, 10,  0,  1, 12, 12, 15,  5,  0,  9,  0,
        1, 13,  0,  0, 11, 14,  0, 13,  8, 12, 11, 11,  0,  0,  8,  0, 14,
       11,  9, 12,  1, 15, 12,  0, 15,  0, 12, 15, 13, 12,  0,  9, 14, 15,
       14, 12, 12,  9,  0, 13,  9,  0,  6, 15, 11,  1, 13, 10,  0, 12,  9,
       14,  0, 10,  0, 12, 10,  0,  0, 15, 15, 15, 10,  0,  9, 12, 13,  0,
       12, 15, 12, 12, 12,  0,  1, 14, 10, 12, 12,  5,  0, 14, 15,  8, 14,
       12,  0,  0,  0,  8, 11,  0,  8,  0, 12,  8, 13, 12,  0,  3, 11,  0,
        9, 10,  5, 13, 14,  0, 11,  4,  3, 12,  0, 10,  8, 14, 14, 11, 15,
       15,  0, 11,  1,  0,  3, 15, 12, 12, 12,  6,  0,  2, 12, 12, 13, 13,
       10, 11, 15,  0, 14, 15,  0,  2,  9,  0, 11, 15,  3,  1,  3, 12, 10,
        8,  7,  9, 15, 13,  5,  0, 12, 13,  6,  4, 10, 14, 11, 13,  9,  0,
       14,  8, 10,  0, 14,  1, 12,  0,  6,  3, 13,  6,  0,  0,  9, 10,  8,
        6,  9, 12,  9, 11, 11, 12,  9,  8, 13,  9,  9,  0, 12, 12, 13,  0,
        0, 11,  4, 11, 14,  0, 11, 12, 11, 12, 12, 12, 14, 11, 12],
      dtype=int32)]

In [12]:

hw_frame = pd.read_csv('filterdatasetnoname.csv', delimiter=',',header=1, names=['KODERS', 'TTD', 'TM', 'DPRS'])
hw_frame.drop('KODERS', 1, inplace=True)
print(hw_frame.head(5))
  
ScatterPlot(hw_frame.TTD, hw_frame.TM, hw_frame.DPRS)

   TTD   TM  DPRS
0   77  161     0
1  420  245    12
2  156  437    15
3  339  178    14
4   47   98    13

NameError: name 'ScatterPlot' is not defined

In [13]:
def input_fn():
    return tf.constant(hw_frame.values, tf.float32, hw_frame.shape), None

In [14]:
tf.logging.set_verbosity(tf.logging.ERROR)
kmeans = tf.contrib.learn.KMeansClustering(num_clusters=5, relative_tolerance=0.0001)
_ = kmeans.fit(input_fn=input_fn)

In [15]:
clusters = kmeans.clusters()
assignments = list(kmeans.predict_cluster_idx(input_fn=input_fn))

In [16]:
ScatterPlot(hw_frame.TTD, hw_frame.TM, assignments, clusters)

NameError: name 'ScatterPlot' is not defined

In [ ]:
%matplotlib notebook

import numpy as np
import pylab 
x = np.linspace(0, 20, 1000)
y1 = np.sin(x)
y2 = np.cos(x)

pylab.plot(x, y1, '-b', label='sine')
pylab.plot(x, y2, '-r', label='cosine')
pylab.legend(loc='upper left')
pylab.ylim(-1.5, 2.0)
pylab.show()